### ISSUE TITLE
燃动夏季node执行异常

### ISSUE THREAD

**Issue by Kaol-Fu** [zero205/JD_tencent_scf#101]
出现如下错误：
❗️燃动夏季, 错误!
TypeError: Cannot read property 'init' of undefined
    at MovementFaker.init (/scripts/jd_summer_movement.js:873:6524)
    at async MovementFaker.run (/scripts/jd_summer_movement.js:873:4853)
    at async getBody (/scripts/jd_summer_movement.js:873:8584)
    at async /scripts/jd_summer_movement.js:708:19
{"code":"1","echo":"required string parameter 'functionId' is not present"}
(node:29665) Warning: Label 'MovementFaker' already exists for console.time()

**Comment by 3136083906** [comment]
一样
