### ISSUE TITLE
部署不上腾讯云

### ISSUE THREAD

**Issue by Cyj97** [zero205/JD_tencent_scf#13]
部署了 腾讯云里没变化是什么原因？
Run node tencentscf.js
TypeError: Cannot read property 'then' of undefined
    at /home/runner/work/***/***/tencentscf.js:25:33
    at Object.<anonymous> (/home/runner/work/***/***/tencentscf.js:171:3)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
写入action.js成功
(node:1728) UnhandledPromiseRejectionWarning: TypeError: cb is not a function
    at ScfClient.failRequest (/home/runner/work/***/***/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:65:9)
    at /home/runner/work/***/***/node_modules/tencentcloud-sdk-nodejs/tencentcloud/common/abstract_client.js:79:102
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![image](https://user-images.githubusercontent.com/26769651/119976179-4de3ec00-bfe9-11eb-9caf-75c329db454c.png)

**Comment by etmty** [comment]
+1，一样的报错

**Comment by Cyj97** [comment]
更新之后好了
