### ISSUE TITLE
beauty能正常运行吗？

### ISSUE THREAD

**Issue by GaviTate** [zero205/JD_tencent_scf#142]
日志报错中止了，不知道能不能用呢

日志:
START RequestId:81738a03-5905-4c2b-bc7a-adb4c8fd47c0
2021-07-29T03:07:02.151Z 81738a03-5905-4c2b-bc7a-adb4c8fd47c0 /var/user/jd_beauty.js:324
            console.log(`【${vo?.data?.position}】上正在生产【${vo?.data?.material_name}】，可收取 ${vo.data.produce_num} 份`)                               ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Runtime.exports.main_handler [as handler] (/var/user/index.js:11:9)
    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)
    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

**Comment by Ca11back** [comment]
这个只能本地运行,云函数尚未转义,本地用也是残缺,收益少,不建议折腾,想用的话可以参考health进行转义,欢迎PR,

**Comment by GaviTate** [comment]
> 参考health进行转义

@Ca11back 谢谢。现在提示其他问题了，能解吗
2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11 "Response code 403 (Forbidden)"
2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11 美丽研究院 API请求失败，请检查网路重试
2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11
提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)

**Comment by Ca11back** [comment]
> > 参考health进行转义
> 
> @Ca11back 谢谢。现在提示其他问题了，能解吗
> 2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11 "Response code 403 (Forbidden)"
> 2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11 美丽研究院 API请求失败，请检查网路重试
> 2021-07-29T07:42:02.867Z 7a5f4701-dda7-4d24-ab83-ffabb69e4e11
> 提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)

感觉可以尝试下ip直连?

**Comment by GaviTate** [comment]
我猜是活动接口换了。
还是不跑算了
