### ISSUE TITLE
部分失效报错

### ISSUE THREAD

**Issue by Ptestq** [zero205/JD_tencent_scf#164]
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/JDJRValidator_Smiek.js
- /ql/scripts/zero205_JD_tencent_scf_jd_joy_steal.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/JDJRValidator_Smiek.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/JDJRValidator_Smiek.js',
    '/ql/scripts/zero205_JD_tencent_scf_jd_joy_steal.js'
  ]
}

## 执行结束... 2021-08-14 12:31:28  耗时 0 秒

internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/JDJRValidator_Smiek.js
- /ql/scripts/zero205_JD_tencent_scf_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/JDJRValidator_Smiek.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/ql/scripts/JDJRValidator_Smiek.js',
    '/ql/scripts/zero205_JD_tencent_scf_jd_joy.js'
  ]
}

**Comment by Ca11back** [comment]
请把package.json内依赖安装全,感谢.
