### ISSUE TITLE
求教！为什么我腾讯云函数部署，没有报错，但是每次执行日志都一样，哪里出错了呢？

### ISSUE THREAD

**Issue by beijing321** [zero205/JD_tencent_scf#23]
按照大佬的教程一步一步做了，可是为什么还是会出错呢，在腾讯云函数里测试的时候，不管测试哪个.js文件，返回结果都为null，日志总是相同的，日志如下：
2021-06-09T05:15:07.785Z 469358ad-eb72-4724-9ad3-6653defcdb80 TypeError: Cannot read property 'split' of undefined
    at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)
    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)
    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Response RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 RetMsg:null
END RequestId:469358ad-eb72-4724-9ad3-6653defcdb80
Report RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 Duration:5ms Memory:128MB MemUsage:9.621094MB

github处配置的scret如下：
JD_COOKIE
PAT
SCF_REGION=ap-guangzhou
TENCENTSCF_SOURCE_TYPE=custom
TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
TENCENT_FUNCTION_NAME=JD
TENCENT_SECRET_ID
TENCENT_SECRET_KEY

云函数处显示的环境变量为：
JD_COOKIE=自己的key和pin;
TENCENTSCF_SOURCE_TYPE=custom
TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
JDCFD_SHARECODES=2ACE2A524E87CFE3C6984213642144027EACC88E6938957CDA9984C30EB98575@37E04B22BDF86E3C3AAC578CC486BB8E15991492EABBD6D8458DEFD7D5E94D91@390051DBC6BB271E4868A98560AE67FB4EE1A54F9B3161BCEC7D26DCA1FC2BC4@A7BDD1C9A8337C93A8CC288AA6963AE83E50BFED3BCE97F52B4B9A061A0C0532@DE25E07F269BEFA8FF3988F4BB2BE35804CCF63D68E4ECFA9320E4E81046DC60@

可以问下是哪里出错了吗？谢谢大佬们！！！

**Comment by no1gc1** [comment]
也一样null

**Comment by no1gc1** [comment]
你几个账号？

**Comment by beijing321** [comment]
> 你几个账号？

就一个

**Comment by beijing321** [comment]
> 你几个账号？
哥，你弄好了吗

**Comment by zero205** [comment]
看日志，定时运行没问题就可以

**Comment by beijing321** [comment]
> 看日志，定时运行没问题就可以

不太行，我选择了 “测试模版：Timer定时器触发事件模版” ，然后点击了测试按钮，日志报错如下：

START RequestId:0c6997b0-1a22-4f21-907a-baa123f32a8d
2021-06-09T09:11:42.634Z 0c6997b0-1a22-4f21-907a-baa123f32a8d user define msg body
ERROR RequestId:0c6997b0-1a22-4f21-907a-baa123f32a8d Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token ':'\n    at Request._callback (/var/user/index.js:26:27)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}
END RequestId:0c6997b0-1a22-4f21-907a-baa123f32a8d

Report RequestId:0c6997b0-1a22-4f21-907a-baa123f32a8d Duration:1906ms Memory:128MB MemUsage:19.585938MB

**Comment by no1gc1** [comment]
START RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4

2021-06-09T10:08:00.224Z 26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 jd_daily_egg

2021-06-09T10:08:00.224Z 26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 jd_carnivalcity

Response RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 RetMsg:null

END RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4

Report RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 Duration:1ms Memory:128MB MemUsage:14.117188MB

**Comment by no1gc1** [comment]
RetMsg:null
没跑出来的原因是啥啊？

**Comment by Poseidon9522** [comment]
> START RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4
> 
> 2021-06-09T10:08:00.224Z 26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 jd_daily_egg
> 
> 2021-06-09T10:08:00.224Z 26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 jd_carnivalcity
> 
> Response RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 RetMsg:null
> 
> END RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4
> 
> Report RequestId:26b85cf6-2255-4cf2-83f3-5d6c07dd3ca4 Duration:1ms Memory:128MB MemUsage:14.117188MB

我的也是这样，不知道咋回事

**Comment by no1gc1** [comment]
RetMsg:null

**Comment by no1gc1** [comment]
> 按照大佬的教程一步一步做了，可是为什么还是会出错呢，在腾讯云函数里测试的时候，不管测试哪个.js文件，返回结果都为null，日志总是相同的，日志如下：
> 2021-06-09T05:15:07.785Z 469358ad-eb72-4724-9ad3-6653defcdb80 TypeError: Cannot read property 'split' of undefined
> at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)
> at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)
> at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)
> at listOnTimeout (internal/timers.js:549:17)
> at processTimers (internal/timers.js:492:7)
> Response RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 RetMsg:null
> END RequestId:469358ad-eb72-4724-9ad3-6653defcdb80
> Report RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 Duration:5ms Memory:128MB MemUsage:9.621094MB
> 
> github处配置的scret如下：
> JD_COOKIE
> PAT
> SCF_REGION=ap-guangzhou
> TENCENTSCF_SOURCE_TYPE=custom
> TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
> TENCENT_FUNCTION_NAME=JD
> TENCENT_SECRET_ID
> TENCENT_SECRET_KEY
> 
> 云函数处显示的环境变量为：
> JD_COOKIE=自己的key和pin;
> TENCENTSCF_SOURCE_TYPE=custom
> TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
> JDCFD_SHARECODES=2ACE2A524E87CFE3C6984213642144027EACC88E6938957CDA9984C30EB98575@37E04B22BDF86E3C3AAC578CC486BB8E15991492EABBD6D8458DEFD7D5E94D91@390051DBC6BB271E4868A98560AE67FB4EE1A54F9B3161BCEC7D26DCA1FC2BC4@A7BDD1C9A8337C93A8CC288AA6963AE83E50BFED3BCE97F52B4B9A061A0C0532@DE25E07F269BEFA8FF3988F4BB2BE35804CCF63D68E4ECFA9320E4E81046DC60@
> 
> 可以问下是哪里出错了吗？谢谢大佬们！！！

你解决了吗？

**Comment by beijing321** [comment]
> > 按照大佬的教程一步一步做了，可是为什么还是会出错呢，在腾讯云函数里测试的时候，不管测试哪个.js文件，返回结果都为null，日志总是相同的，日志如下：
> > 2021-06-09T05:15:07.785Z 469358ad-eb72-4724-9ad3-6653defcdb80 TypeError: Cannot read property 'split' of undefined
> > at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)
> > at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)
> > at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)
> > at listOnTimeout (internal/timers.js:549:17)
> > at processTimers (internal/timers.js:492:7)
> > Response RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 RetMsg:null
> > END RequestId:469358ad-eb72-4724-9ad3-6653defcdb80
> > Report RequestId:469358ad-eb72-4724-9ad3-6653defcdb80 Duration:5ms Memory:128MB MemUsage:9.621094MB
> > github处配置的scret如下：
> > JD_COOKIE
> > PAT
> > SCF_REGION=ap-guangzhou
> > TENCENTSCF_SOURCE_TYPE=custom
> > TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
> > TENCENT_FUNCTION_NAME=JD
> > TENCENT_SECRET_ID
> > TENCENT_SECRET_KEY
> > 云函数处显示的环境变量为：
> > JD_COOKIE=自己的key和pin;
> > TENCENTSCF_SOURCE_TYPE=custom
> > TENCENTSCF_SOURCE_URL=https://gitee.com/zero205/JD_tencent_scf/raw/main/
> > JDCFD_SHARECODES=2ACE2A524E87CFE3C6984213642144027EACC88E6938957CDA9984C30EB98575@37E04B22BDF86E3C3AAC578CC486BB8E15991492EABBD6D8458DEFD7D5E94D91@390051DBC6BB271E4868A98560AE67FB4EE1A54F9B3161BCEC7D26DCA1FC2BC4@A7BDD1C9A8337C93A8CC288AA6963AE83E50BFED3BCE97F52B4B9A061A0C0532@DE25E07F269BEFA8FF3988F4BB2BE35804CCF63D68E4ECFA9320E4E81046DC60@
> > 可以问下是哪里出错了吗？谢谢大佬们！！！
> 
> 你解决了吗？

并没有，你解决了吗？

**Comment by dg931** [comment]
2021-06-10T09:36:10.149Z 82a5f8d7-a68d-4af3-839e-7f134d7ddb58 省钱大赢家之翻翻乐 API请求失败，请检查网路重试
5个号助力有的就做了前面的两三个号后就没做，好多js执行都出错

**Comment by zhangdaren3389** [comment]
同样也是这样。。。
