### ISSUE TITLE
jd_bean_sign.js脚本运行出错

### ISSUE THREAD

**Issue by SQDFeng** [zero205/JD_tencent_scf#233]
main block finished
Nobyda签到部分开始
ERRROR: /home/feng/jd/scripts/JDSignValidator.js:208
    f = {
      ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at then (/home/feng/jd/scripts/jd_bean_sign.js:125:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Ca11back** [comment]
环境?不太应该
