### ISSUE TITLE
jd_redPacket互助报错

### ISSUE THREAD

**Issue by kaifeiji** [zero205/JD_tencent_scf#259]
# 模块：jd_redPacket

## 问题

组内互助时报错

❗️京东全民开红包, 错误!
TypeError: Cannot read property 'statusDesc' of undefined
    at xxx\jd_redPacket.js:425:50
    at got.post.then.message (xxx\jd_redPacket.js:705:5677)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

## 请求参数

```
{
  url: 'https://api.m.jd.com/api?appid=jinlihongbao&functionId=jinli_h5assist&loginType=2&client=jinlihongbao&clientVersion=10.1.0&osVersion=iOS&d_brand=iPhone&d_model=iPhone&t=1635832548580000',
  body: 'body=%7B%22clientInfo%22%3A%7B%7D%2C%22redPacketId%22%3A379979461%2C%22followShop%22%3A0%2C%22promUserState%22%3A%22%22%7D'
  headers: {
    Accept: '*/*'
    Accept-Encoding: 'gzip, deflate, br'
    Accept-Language: 'zh-cn'
    Connection: 'keep-alive'
    Content-Length: '56'
    Content-Type: 'application/x-www-form-urlencoded'
    Cookie: 'pt_key=xxx;pt_pin=xxx;'
    Host: 'api.m.jd.com'
    Origin: 'https://happy.m.jd.com'
    Referer: 'https://happy.m.jd.com/babelDiy/zjyw/3ugedFa7yA6NhxLN5gw2L3PF9sQC/index.html'
    User-Agent: 'jdapp;android;10.1.6;9;network/wifi;Mozilla/5.0 (Linux; Android 9; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.126 MQQBrowser/6.2 TBS/044942 Mobile Safari/537.36'
  }
}
```

## 返回结果

没有了`result.statusDesc`这个字段，是返回数据的结构变了？还是我账号的问题？

```
'{"code":0,"data":{"biz_code":0,"code":0,"rtn_code":403,"success":true},"rtn_code":403}'
```

**Comment by Ca11back** [comment]
应该是结构变了,实际应该不影响吧,等着修复下输出就好了
