### ISSUE TITLE
为什么腾讯云函数的日志查询里全是报错的

### ISSUE THREAD

**Issue by rececece** [zero205/JD_tencent_scf#29]
查询了下腾讯云函数的日志，期中有好多提示“调用失败”，求大佬帮忙解决，跪谢！！！
部分提示“调用失败”的日志如下：
（1）
日志:
START RequestId:7d51b0d9-037b-4305-8eee-b09ef245face
2021-06-09T14:01:02.179Z 7d51b0d9-037b-4305-8eee-b09ef245face jd_half_redrain
2021-06-09T14:01:02.330Z 7d51b0d9-037b-4305-8eee-b09ef245face
2021-06-09T14:01:02.330Z 7d51b0d9-037b-4305-8eee-b09ef245face jd_z_health_community
2021-06-09T14:01:02.331Z 7d51b0d9-037b-4305-8eee-b09ef245face jd_zooCollect
2021-06-09T14:01:02.331Z 7d51b0d9-037b-4305-8eee-b09ef245face jd_kj
ERROR RequestId:7d51b0d9-037b-4305-8eee-b09ef245face Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token '\u003c'\n    at Request._callback (/var/user/index.js:26:27)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}
END RequestId:7d51b0d9-037b-4305-8eee-b09ef245face
Report RequestId:7d51b0d9-037b-4305-8eee-b09ef245face Duration:389ms Memory:128MB MemUsage:17.003906MB

（2）
START RequestId:5fc9515c-914d-4795-ab9b-95bf12cb5681
2021-06-09T13:31:03.148Z 5fc9515c-914d-4795-ab9b-95bf12cb5681 jd_half_redrain
2021-06-09T13:31:03.270Z 5fc9515c-914d-4795-ab9b-95bf12cb5681
2021-06-09T13:31:03.270Z 5fc9515c-914d-4795-ab9b-95bf12cb5681 jd_z_health_community
2021-06-09T13:31:03.271Z 5fc9515c-914d-4795-ab9b-95bf12cb5681 jd_zooCollect
2021-06-09T13:31:03.271Z 5fc9515c-914d-4795-ab9b-95bf12cb5681 jd_kj
ERROR RequestId:5fc9515c-914d-4795-ab9b-95bf12cb5681 Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Unexpected token '.'\n    at Request._callback (/var/user/index.js:26:27)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}
END RequestId:5fc9515c-914d-4795-ab9b-95bf12cb5681
Report RequestId:5fc9515c-914d-4795-ab9b-95bf12cb5681 Duration:375ms Memory:128MB MemUsage:16.921875MB

（3）
START RequestId:a9077be9-22b0-4622-b197-6ce7d55f421e
2021-06-09T13:20:00.110Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_pigPet
2021-06-09T13:20:00.252Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_syj
2021-06-09T13:20:00.252Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_kd
2021-06-09T13:20:00.252Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_jxlhb
2021-06-09T13:20:00.253Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_jdzz
2021-06-09T13:20:00.253Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_nzmh
2021-06-09T13:20:00.253Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_monk_shop_follow_sku
2021-06-09T13:20:00.254Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_jump
2021-06-09T13:20:00.254Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_mcxhd
2021-06-09T13:20:00.254Z a9077be9-22b0-4622-b197-6ce7d55f421e jd_star_shop

ERROR RequestId:a9077be9-22b0-4622-b197-6ce7d55f421e Result:{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"SyntaxError: Invalid or unexpected token\n    at Request._callback (/var/user/index.js:26:27)\n    at Request.self.callback (/var/user/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:311:20)\n    at Request.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1154:10)\n    at Request.emit (events.js:311:20)\n    at IncomingMessage.\u003canonymous\u003e (/var/user/node_modules/request/request.js:1076:12)\n    at Object.onceWrapper (events.js:417:28)\n    at IncomingMessage.emit (events.js:323:22)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","statusCode":430}
END RequestId:a9077be9-22b0-4622-b197-6ce7d55f421e
Report RequestId:a9077be9-22b0-4622-b197-6ce7d55f421e Duration:426ms Memory:128MB MemUsage:15.164062MB

求大佬帮忙解决，跪谢！！！！

**Comment by Ca11back** [comment]
部署问题,请自行檢查,请同步最新库,如有问题再带日志反馈
