### ISSUE TITLE
京东生鲜每日抽奖, 错误!

### ISSUE THREAD

**Issue by MarcioXIN** [zero205/JD_tencent_scf#306]
京东生鲜每日抽奖, 错误!
TypeError: Cannot read properties of null (reading 'chanceLeft')
    at /ql/scripts/zero205_JD_tencent_scf_main/jd_sxLottery.js:171:46
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/zero205_JD_tencent_scf_main/jd_sxLottery.js:381:5617)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: $.taskinfo is not iterable
    at run (/ql/scripts/zero205_JD_tencent_scf_main/jd_sxLottery.js:99:26)
    at jdmodule (/ql/scripts/zero205_JD_tencent_scf_main/jd_sxLottery.js:81:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /ql/scripts/zero205_JD_tencent_scf_main/jd_sxLottery.js:55:13

**Comment by Ca11back** [comment]
已经移除
