### ISSUE TITLE
云函数运行异常

### ISSUE THREAD

**Issue by xukaishan** [zero205/JD_tencent_scf#339]
2022-02-05T07:36:35.771Z bb8fca94-ca6a-435c-bbcc-fd74f1dc240b 参数触发方式:未接收到任何参数,请阅读@hshx123大佬教程的测试步骤,查看如何使用.

2022-02-05T01:59:50.667Z 90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 参数触发方式(不读取配置文件),触发参数: jd_cfd_pearl_ex

2022-02-05T01:59:50.669Z 90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 当前是 异 步执行

2022-02-05T01:59:50.669Z 90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 异步执行不支持params参数

2022-02-05T01:59:50.669Z 90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 index:168: run script:jd_cfd_pearl_ex

2022-02-05T01:59:50.669Z 90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 index:173: 异步jd_cfd_pearl_ex异常: Error: Cannot find module './jd_cfd_pearl_ex.js'

Require stack:

- /var/user/index.js

- /var/runtime/node12/UserFunction.js

- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)

    at Function.Module._load (internal/modules/cjs/loader.js:864:27)

    at Module.require (internal/modules/cjs/loader.js:1044:19)

    at require (internal/modules/cjs/helpers.js:77:18)

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:171:17)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/var/user/index.js',

    '/var/runtime/node12/UserFunction.js',

    '/var/runtime/node12/Runtime.engine.js',

    '/var/runtime/node12/bootstrap.js'

  ]

}

Response RequestId:90a7d17f-5047-4cbc-9ee7-2029dcaa1f79 RetMsg:null

**Comment by Ca11back** [comment]
https://github.com/zero205/JD_tencent_scf/tree/scf2#%E4%BB%93%E5%BA%93%E5%AD%98%E5%9C%A8%E7%9A%84%E6%96%87%E4%BB%B6%E4%BA%91%E5%87%BD%E6%95%B0%E6%8A%A5cannot-find-the-moudle%E5%87%BD%E6%95%B0%E7%BC%BA%E6%96%87%E4%BB%B6%E5%8F%AA%E6%9C%89%E5%87%A0%E4%B8%AA%E6%96%87%E4%BB%B6
