### ISSUE TITLE
部署到云函数报错了user define msg body。请大佬指教，谢谢

### ISSUE THREAD

**Issue by zhangdaren3389** [zero205/JD_tencent_scf#41]
START RequestId:46776b55-31d8-4669-bd32-7a01a2a0b512

2021-06-11T15:56:38.786Z  46776b55-31d8-4669-bd32-7a01a2a0b512  user define msg body

2021-06-11T15:56:39.071Z  46776b55-31d8-4669-bd32-7a01a2a0b512  Error: Cannot find module './user define msg body.js'

Require stack:

- /var/user/index.js

- /var/runtime/node12/UserFunction.js

- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)

    at Function.resolve (internal/modules/cjs/helpers.js:83:19)

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:10:36)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:217:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7) {

  code: 'MODULE_NOT_FOUND',

  requireStack: [

    '/var/user/index.js',

    '/var/runtime/node12/UserFunction.js',

    '/var/runtime/node12/Runtime.engine.js',

    '/var/runtime/node12/bootstrap.js'

  ]

}

Response RequestId:46776b55-31d8-4669-bd32-7a01a2a0b512 RetMsg:null

END RequestId:46776b55-31d8-4669-bd32-7a01a2a0b512

Report RequestId:46776b55-31d8-4669-bd32-7a01a2a0b512 Duration:301ms Memory:128MB MemUsage:16.238281MB

**Comment by stitchmaps** [comment]
我也遇到了，解决了吗兄弟

**Comment by Ca11back** [comment]
更新代码,如果还有问题,请带详细日志去群内反馈
