### ISSUE TITLE
新版宠汪汪无法运行

### ISSUE THREAD

**Issue by Hyper-Beast** [zero205/JD_tencent_scf#70]
从日志看是缺了运行库
![image](https://user-images.githubusercontent.com/18001712/123044564-6d293a00-d42c-11eb-803e-af7fb00bc876.png)

**Comment by hoogyuan** [comment]
差不多的问题
🔔宠汪汪二代目, 开始!

====================Hello World====================

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'png-js'
Require stack:
- /ql/scripts/zero205_JD_tencent_scf_jd_joy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/ql/scripts/zero205_JD_tencent_scf_jd_joy.js:20:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/ql/scripts/zero205_JD_tencent_scf_jd_joy.js' ]
}

**Comment by hoogyuan** [comment]
“png-js“不知道是不是用来过验证码的脚本

**Comment by zero205** [comment]
> “png-js“不知道是不是用来过验证码的脚本

是的。尝试修复了，现在能运行了吗？

**Comment by linyali888** [comment]
> > “png-js“不知道是不是用来过验证码的脚本
> 
> 是的。尝试修复了，现在能运行了吗？

一样还是不行

**Comment by linyali888** [comment]
> > “png-js“不知道是不是用来过验证码的脚本
> 
> 是的。尝试修复了，现在能运行了吗？

还要是下png-js这个？去哪下

**Comment by hoogyuan** [comment]
可以运行，不报错了，但是会提示环境检测失败

开始执行... 2021/6/24 上午9:00:22

更新任务状态成功

🔔宠汪汪二代目, 开始!

====================Hello World====================

您的cookie选择的是用&隔开


====================共有2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/6/24 上午9:00:23=====================

共7个京东账号


【京东账号1】***********：运行环境检测失败


【京东账号2】***********：运行环境检测失败


更新任务状态成功

执行结束...

**Comment by hoogyuan** [comment]
修改JS_USER_AGENTS.js文件后可以正常运行了

**Comment by Hyper-Beast** [comment]
> 修改JS_USER_AGENTS.js文件后可以正常运行了

请问怎么改

**Comment by Hyper-Beast** [comment]
安装了png-js再改了JS_USER_AGENTS.js后可以了
