### ISSUE TITLE
美丽研究院在elecV2P运行报错

### ISSUE THREAD

**Issue by kkmatriz02** [zero205/JD_tencent_scf#9]
const WebSocket = require('ws');
                  ^

ReferenceError: require is not defined
    at jd_beauty.js:13:19
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:301:38)
    at /usr/local/app/script/runJSFile.js:192:24
    at new Promise (<anonymous>)
    at runJS (/usr/local/app/script/runJSFile.js:168:10)
    at /usr/local/app/script/runJSFile.js:289:5
    at new Promise (<anonymous>)
    at runJSFile (/usr/local/app/script/runJSFile.js:288:10)

**Comment by zero205** [comment]
美丽研究院脚本暂不支持在elecV2P上运行，可以尝试在云函数上跑试试
