### ISSUE TITLE
京东试用依然没有修复，运行就报错

### ISSUE THREAD

**Issue by testmemory** [zero205/JD_tencent_scf#92]

**Comment by testmemory** [comment]
START RequestId:847edba1-ab1f-4d42-a704-7a8c2160aea0

2021-07-06T14:28:17.560Z 847edba1-ab1f-4d42-a704-7a8c2160aea0 TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:7:38)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:219:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:56:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

Response RequestId:847edba1-ab1f-4d42-a704-7a8c2160aea0 RetMsg:null

END RequestId:847edba1-ab1f-4d42-a704-7a8c2160aea0

Report RequestId:847edba1-ab1f-4d42-a704-7a8c2160aea0 Duration:4ms Memory:64MB MemUsage:11.613281MB
部署在云函数上，运行后报错如上

**Comment by zero205** [comment]
看你这个报错日志，你是直接点的测试的吧

**Comment by testmemory** [comment]
确实是的，但是试用也确确实实从3号被删掉之后再也没正常运行过

**Comment by zero205** [comment]
> 确实是的，但是试用也确确实实从3号被删掉之后再也没正常运行过

请把报错日志贴出来。你上面那个直接点测试的方法是错的。教程有写怎么测试脚本

**Comment by testmemory** [comment]
虽然工单告诉我异步执行的云函数不能开启调试模式测试，但是今天试用脚本又正常执行了，，，
